version: '3.8'

services:
  api:
    image: unirota/unirota-api:latest
    build:
      context: .
      dockerfile: ./src/Unirota.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=User ID=unirota_admin;Password=fkywW9##b6Fkc%^;Host=unirota-db-instance.cxeqekys2w8q.us-east-2.rds.amazonaws.com;Port=5432;Database=postgres;Pooling=true;
    networks:
      - unirota-network

networks:
  unirota-network:
    driver: bridge
